// <auto-generated />
namespace EventServiceApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedtransport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedtransport));
        
        string IMigrationMetadata.Id
        {
            get { return "202012061047048_added-transport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
